stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: internal_digiapi



build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
  only:
    - main
  tags:
    - ff-dj-docker1

before_script:
  - apt-get install -y npm
  - npm install

test:
  stage: test
  script:
    - npm test -- --coverage
  only:
    - main
  tags:
    - ff-dj-docker1
  artifacts:
    paths:
      - coverage/

deploy:
  stage: deploy
  script:
    - docker stop $IMAGE_NAME || true
    - docker rm $IMAGE_NAME || true
    - docker run -d -p 3000:3000 --name $IMAGE_NAME $IMAGE_NAME
    - sleep 10  # Give the container some time to start
    - if [ "$(docker inspect -f {{.State.Running}} $IMAGE_NAME)" = "false" ]; then docker logs $IMAGE_NAME; exit 1; fi
  only:
    - main
  tags:
    - ff-dj-docker1


